DROP DATABASE IF EXISTS compta;
CREATE DATABASE IF NOT EXISTS compta; 

USE compta;

DROP TABLE IF EXISTS ARTICLE;
CREATE TABLE IF NOT EXISTS ARTICLE (
    ID INT(11) PRIMARY KEY,
    REF VARCHAR(13),
    DESIGNATION VARCHAR(255),
    PRIX DECIMAL(7,2),
    ID_FOU INT(11)
);

DROP TABLE IF EXISTS FOURNISSEUR;
CREATE TABLE IF NOT EXISTS FOURNISSEUR (
    ID INT(11) PRIMARY KEY, 
    NOM VARCHAR(25)
);

DROP TABLE IF EXISTS BON;
CREATE TABLE IF NOT EXISTS BON (
    ID INT(11) PRIMARY KEY,
    NUMERO INT(11),
    DATE_CMDE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DELAI INT(11),
    ID_FOU INT(11)
);

DROP TABLE IF EXISTS COMPO;
CREATE TABLE IF NOT EXISTS COMPO (
    ID INT(11) PRIMARY KEY,
    ID_ART INT(11),
    ID_BON INT(11),
    QTE INT(11)
);

ALTER TABLE ARTICLE ADD CONSTRAINT FOREIGN KEY (ID_FOU) REFERENCES FOURNISSEUR(ID);
ALTER TABLE BON ADD CONSTRAINT FOREIGN KEY (ID_FOU) REFERENCES FOURNISSEUR(ID);
ALTER TABLE COMPO ADD CONSTRAINT FOREIGN KEY (ID_ART) REFERENCES ARTICLE(ID);
ALTER TABLE COMPO ADD CONSTRAINT FOREIGN KEY (ID_BON) REFERENCES BON(ID);

