USE compta

SELECT * 
FROM ARTICLE 
ORDER BY DESIGNATION

SELECT *
FROM ARTICLE
ORDER BY PRIX DESC

SELECT *
FROM ARTICLE
WHERE DESIGNATION 
LIKE 'B%'
ORDER BY PRIX 

SELECT * 
FROM ARTICLE
WHERE DESIGNATION LIKE '%SACHET%'

SELECT * 
FROM ARTICLE, FOURNISSEUR
ORDER BY FOURNISSEUR.NOM, PRIX DESC

SELECT *
FROM ARTICLE, FOURNISSEUR 
WHERE ARTICLE.ID_FOU = FOURNISSEUR.ID 
AND NOM = 'Dubois & fils';

SELECT AVG(PRIX)
FROM ARTICLE, FOURNISSEUR
WHERE ARTICLE.ID_FOU = FOURNISSEUR.ID 
AND NOM = 'Dubois & fils';

SELECT FOURNISSEUR.NOM, AVG(PRIX)
FROM ARTICLE, FOURNISSEUR
WHERE ARTICLE.ID_FOU = FOURNISSEUR.ID 
GROUP BY FOURNISSEUR.NOM


SELECT *
FROM BON
WHERE DATE_CMDE BETWEEN "2019-03-01" AND "2019-04-05 12:00:00"


SELECT *
FROM BON, ARTICLE, FOURNISSEUR
WHERE BON.ID_FOU = FOURNISSEUR.ID 
AND  FOURNISSEUR.ID = ARTICLE.ID_FOU
AND ARTICLE.DESIGNATION 
LIKE '%boulon%'

SELECT *
FROM BON, ARTICLE, FOURNISSEUR
WHERE BON.ID_FOU = FOURNISSEUR.ID 
AND FOURNISSEUR.ID = ARTICLE.ID_FOU 
AND ARTICLE.DESIGNATION
LIKE '%boulon%'

SELECT BON.NUMERO, SUM(ARTICLE.PRIX * COMPO.QTE)
FROM BON
JOIN COMPO 
ON BON.ID = COMPO.ID_BON
JOIN ARTICLE
ON COMPO.ID_ART = ARTICLE.ID
GROUP BY BON.NUMERO

SELECT 
FROM BON
LEFT JOIN (COMPO LEFT JOIN ARTICLE ON COMPO.ID_ART = ARTICLE.ID) ON BON.ID = COMPO.ID_BON
GROUP BY BON.ID





